# TCL File Generated by Component Editor 20.1
# Thu Jul 07 12:34:18 JST 2022
# DO NOT MODIFY


# 
# ImageFilter "ImageFilter" v1.0
# Takaaki Toda 2022.07.07.12:34:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ImageFilter
# 
set_module_property DESCRIPTION ""
set_module_property NAME ImageFilter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Takaaki Toda"
set_module_property DISPLAY_NAME ImageFilter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ImageFilter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Convolver.v VERILOG PATH submodules/Convolver.v
add_fileset_file GrayscaleConverter.v VERILOG PATH submodules/GrayscaleConverter.v
add_fileset_file ImageFilter.v VERILOG PATH submodules/ImageFilter.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ImageFilter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Convolver.v VERILOG PATH submodules/Convolver.v
add_fileset_file GrayscaleConverter.v VERILOG PATH submodules/GrayscaleConverter.v
add_fileset_file ImageFilter.v VERILOG PATH submodules/ImageFilter.v


# 
# parameters
# 
add_parameter BIT_PER_PIXEL INTEGER 8
set_parameter_property BIT_PER_PIXEL DEFAULT_VALUE 8
set_parameter_property BIT_PER_PIXEL DISPLAY_NAME BIT_PER_PIXEL
set_parameter_property BIT_PER_PIXEL TYPE INTEGER
set_parameter_property BIT_PER_PIXEL UNITS None
set_parameter_property BIT_PER_PIXEL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BIT_PER_PIXEL HDL_PARAMETER true
add_parameter NUM_PIXELS INTEGER 9
set_parameter_property NUM_PIXELS DEFAULT_VALUE 9
set_parameter_property NUM_PIXELS DISPLAY_NAME NUM_PIXELS
set_parameter_property NUM_PIXELS TYPE INTEGER
set_parameter_property NUM_PIXELS UNITS None
set_parameter_property NUM_PIXELS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_PIXELS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 4
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point switch_in
# 
add_interface switch_in conduit end
set_interface_property switch_in associatedClock clock
set_interface_property switch_in associatedReset ""
set_interface_property switch_in ENABLED true
set_interface_property switch_in EXPORT_OF ""
set_interface_property switch_in PORT_NAME_MAP ""
set_interface_property switch_in CMSIS_SVD_VARIABLES ""
set_interface_property switch_in SVD_ADDRESS_GROUP ""

add_interface_port switch_in SW export Input 4

